// <auto-generated />
namespace LowFlightFare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_new_Properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_new_Properties));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251846445_adding_new_Properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
