// <auto-generated />
namespace LowFlightFare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removing_resonse_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removing_resonse_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271121385_removing_resonse_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
