// <auto-generated />
namespace LowFlightFare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changing_datetime_fromstring_to_datetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_datetime_fromstring_to_datetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201803202211350_changing_datetime_fromstring_to_datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
