// <auto-generated />
namespace LowFlightFare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class checking_if_all_migrations_are_applied : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checking_if_all_migrations_are_applied));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281004471_checking_if_all_migrations_are_applied"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
