// <auto-generated />
namespace LowFlightFare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_locale_and_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_locale_and_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201803272318202_Added_locale_and_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
